import { StyleSheet } from 'react-native';

// ─── Splash styles ──────────────────────────────────────────────────────────

export const splashStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F8DE22',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoShadow: {
    position: 'absolute',
    top: 8,
    left: 8,
    right: -8,
    bottom: -8,
    backgroundColor: '#111',
    borderRadius: 24,
  },
  logoCard: {
    width: 180,
    height: 180,
    backgroundColor: '#fff',
    borderWidth: 3.5,
    borderColor: '#111',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  kBadge: {
    width: 72,
    height: 72,
    backgroundColor: '#111',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  kText: {
    fontSize: 48,
    fontWeight: '900',
    color: '#F8DE22',
    lineHeight: 56,
  },
  dpRow: {
    backgroundColor: '#F8DE22',
    paddingHorizontal: 16,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#111',
  },
  dpText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#111',
    letterSpacing: 4,
  },
  storeBadge: {
    backgroundColor: '#03AED2',
    paddingHorizontal: 12,
    paddingVertical: 3,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#111',
  },
  storeText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#111',
    letterSpacing: 3,
  },
  tagline: {
    marginTop: 32,
    fontSize: 11,
    fontWeight: '900',
    color: '#111',
    letterSpacing: 2,
  },
  strip: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 44,
    backgroundColor: '#111',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stripText: {
    color: '#F8DE22',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 4,
  },
});

// ─── Admin screen styles ────────────────────────────────────────────────────

export const adminStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F8DE22',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  stripe: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 52,
    backgroundColor: '#111',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stripeText: {
    color: '#F8DE22',
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 3,
  },
  card: {
    width: '100%',
    maxWidth: 360,
    position: 'relative',
  },
  cardShadow: {
    position: 'absolute',
    top: 6,
    left: 6,
    right: -6,
    bottom: -6,
    backgroundColor: '#111',
    borderRadius: 16,
  },
  cardInner: {
    backgroundColor: '#fff',
    borderWidth: 3,
    borderColor: '#111',
    borderRadius: 16,
    padding: 28,
    alignItems: 'center',
    gap: 12,
  },
  emoji: { fontSize: 48 },
  title: {
    fontSize: 22,
    fontWeight: '900',
    color: '#111',
    letterSpacing: 0.5,
  },
  desc: {
    fontSize: 14,
    color: '#444',
    textAlign: 'center',
    lineHeight: 20,
  },
  linkBtn: {
    backgroundColor: '#111',
    color: '#F8DE22',
    fontWeight: '900',
    fontSize: 14,
    textAlign: 'center',
    paddingVertical: 14,
    borderRadius: 10,
    letterSpacing: 0.5,
    overflow: 'hidden',
  },
  logoutBtn: {
    marginTop: 4,
    fontSize: 13,
    color: '#888',
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
});
